name: .NET Core Desktop

on:
  workflow_dispatch: 
    inputs: 
      deployment_target:
        description: Choose target
        required: true
        default: smoke_test
        type: choice
        options:
          - smoke_test
          - regression_test

jobs:

  test:

    strategy:
      matrix:
        configuration: [ Debug ]

    runs-on: ubuntu-latest
    
    #    env:
    #      Solution_Name: your-solution-name                         # Replace with your solution name, i.e. MyWpfApp.sln.
    #      Test_Project_Path: your-test-project-path                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
    #      Wap_Project_Directory: your-wap-project-directory-name    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
    #      Wap_Project_Path: your-wap-project-path                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Execute Smoke tests in the solution
      - name: Execute Smoke tests
        if: "github.event.inputs.deployment_target == 'smoke_test'"
        run: dotnet test --filter Category=Smoke

      # Execute Regression tests in the solution
      - name: Execute Regression tests
        if: "github.event.inputs.deployment_target == 'regression_test'"
        run: dotnet test --filter Category=Regression

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: TestRail/bin/Debug/net8.0/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
 